#steps:
#- name: "gcr.io/cloud-builders/gcloud"
#  args: ["app", "deploy"]
#timeout: "1600s"

substitutions:
  _IMAGE_NAME: esg-ui
  _IMAGE_NAME_DOCKER_CACHE: trading-message-service-cache-subhajit
  _PROJECT_ID: esg-trade-enabler

steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '${_IMAGE_NAME}', '--image', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '--region', 'europe-west2-b', '--allow-unauthenticated']
  env:
  - 'PORT=8080'
images:
- gcr.io/${PROJECT_ID}/${_IMAGE_NAME}