#steps:
#- name: "gcr.io/cloud-builders/gcloud"
#  args: ["app", "deploy"]
#timeout: "1600s"

substitutions:
  _IMAGE_NAME: esg-ui
  _PROJECT_ID: esg-trade-enabler

steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}']
  # deploy container image to Cloud Run
# deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'apply'
  - '-f'
  - 'k8s/'
  - --location=us-west2-b
  - --cluster=esgte-cluster-dev
images:
- gcr.io/${PROJECT_ID}/${_IMAGE_NAME}