apiVersion: v1
kind: Service
metadata:
  labels:
    app: esg-ui-service
  name: esg-ui-service
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    app: esg-ui-service